-- Display the first 10 rows of the dataset.
SELECT *
FROM superstore
LIMIT 10;

-- List all unique ship modes available in the dataset.
SELECT DISTINCT Ship_Mode
FROM superstore;

-- Count the number of orders placed by each customer.
SELECT Customer_Name,
	COUNT(QUANTITY) AS Orders
FROM superstore
GROUP BY Customer_Name;

-- Find the total number of unique customers.
SELECT COUNT(DISTINCT Customer_Name) AS Total_Customers
FROM superstore;

-- Calculate the total sales and profit for each region.
SELECT Region,
	ROUND(SUM(Sales),2) AS Sales,
    ROUND(SUM(Profit),2) AS Profit
FROM superstore
GROUP BY Region;

-- Find the top 5 cities with the highest total sales.
SELECT City,
	ROUND(SUM(Sales),2) AS Highest_Sales
FROM superstore
GROUP BY City
ORDER BY Highest_Sales DESC
LIMIT 5;

-- Calculate the average discount given for each product category.
SELECT Category,
	ROUND(AVG(Discount),2) AS Avg_Discount
FROM superstore
GROUP BY Category;

-- List the top 3 customers based on total profit.
SELECT Customer_Name,
	ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore
GROUP BY Customer_Name
ORDER BY Total_Profit DESC
LIMIT 3;

-- Find the total quantity of items sold per sub-category.
SELECT Sub_Category,
	SUM(Quantity) AS Quantit_Sold
FROM superstore
GROUP BY Sub_Category;

-- Calculate the average profit per order for each segment.
SELECT Segment,
	ROUND(SUM(Profit) / COUNT(DISTINCT Order_ID),2) AS Avg_Profit_Per_Order
FROM superstore
GROUP BY Segment;

-- Find the total profit generated by each ship mode.
SELECT Ship_Mode,
	ROUND(SUM(Profit),2) AS Profit_Of_Each_Ship_Mode
FROM superstore
GROUP BY Ship_Mode;

-- Determine which category contributes the most to total sales.
SELECT Category,
	ROUND(SUM(Sales),2) AS Sales
FROM superstore
GROUP BY Category
ORDER BY Sales DESC
LIMIT 1;
